# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x0b\x66ileservice\"E\n\rUploadRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x10\n\x08\x66iledata\x18\x03 \x01(\x0c\"=\n\x0eUploadResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x18\n\x10\x63over_image_path\x18\x02 \x01(\t\"(\n\x0f\x44ownloadRequest\x12\x15\n\rrelative_path\x18\x01 \x01(\t\"6\n\x10\x44ownloadResponse\x12\x10\n\x08\x66iledata\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t2\xe8\x01\n\x0b\x46ileService\x12\x46\n\x0bUploadImage\x12\x1a.fileservice.UploadRequest\x1a\x1b.fileservice.UploadResponse\x12\x44\n\tUploadPdf\x12\x1a.fileservice.UploadRequest\x1a\x1b.fileservice.UploadResponse\x12K\n\x0c\x44ownloadFile\x12\x1c.fileservice.DownloadRequest\x1a\x1d.fileservice.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=35
  _globals['_UPLOADREQUEST']._serialized_end=104
  _globals['_UPLOADRESPONSE']._serialized_start=106
  _globals['_UPLOADRESPONSE']._serialized_end=167
  _globals['_DOWNLOADREQUEST']._serialized_start=169
  _globals['_DOWNLOADREQUEST']._serialized_end=209
  _globals['_DOWNLOADRESPONSE']._serialized_start=211
  _globals['_DOWNLOADRESPONSE']._serialized_end=265
  _globals['_FILESERVICE']._serialized_start=268
  _globals['_FILESERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
